name: example
description: Demonstrate how golden toolkit can be used to
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  golden_toolkit:
    path: ../

flutter:
  uses-material-design: true
  assets:
    - images/
