name: golden_toolkit
description: Common patterns for screenshot-based widget testing using Goldens.
version: 0.16.0
homepage: https://github.com/fatherOfLegends/golden_toolkit
repository: https://github.com/fatherOfLegends/golden_toolkit
issue_tracker: https://github.com/fatherOfLegends/golden_toolkit/issues

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  meta: ^1.8.0

dev_dependencies:
  flutter_lints: ^4.0.0
  sample_dependency:
    path: test/sample_dependency
  test_api: any

flutter:
  fonts:
    - family: Roboto
      fonts:
        - asset: packages/golden_toolkit/fonts/Roboto-Regular.ttf
